# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152pGclI1yti7bnfoBcAmds20ti2SGeR8

پرسیدن تعداد شرکت کنندگان و برندگان
"""

participants = input("لطفا تعداد شرکت کنندگان را به عدد انگلیسی وارد کنید")
winners = input("لطفا تعداد برندگان را به عدد انگلیسی وارد کنید و این تعداد باید کمتر یا مساوی تعداد شرکت کنندگان باشد ")

"""تبدیل مقادیر اینپوت شده به اینتجر"""

participants2 = int(participants)
winners2 = int(winners)

"""تولید شماره تماس"""

import random
phone_numbers = []
pre = "09"
for i in range(participants2) :
  numbers = random.randint(100000000, 999999999)
  phone_number = f'{pre}{numbers}'
  phone_numbers.append(phone_number)

"""تعیین برندگان"""

import random
our_winners = random.sample(phone_numbers , winners2)
masked_winners = []
for winner in our_winners :
  show_number = winner[ :7]
  star = "***"
  safe_winner = show_number + star
  masked_winners.append(safe_winner)

"""نمایش برندگان"""

print("winners are" , masked_winners)