# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D51mm1vmDxk7_6Yf-9EKo6PBZ9KzuYY8
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_normal_dist(n):
  data = np.random.normal(loc = 0.0, scale = 1.0, size = n)
  plt.hist(data , bins= 100)
  plt.xlabel('Value')
  plt.ylabel('Frequency')
  plt.title(f'Histogram of : (n= {n}, mean= 0, std=1)')
  plt.grid(True)
  plt.show()

plot_normal_dist(10)

plot_normal_dist(1000)

plot_normal_dist(100000)