# -*- coding: utf-8 -*-
"""Plots

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkVZ4B68C0PKH-J9PyYhd-JNO_bL2NpS

Create the plots
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-5,5,200)
y1 = x**3

plt.figure()
plt.plot(x, y1, '--')
plt.title('plot of y=x**3')
plt.xlabel('x')
plt.ylabel('y')
plt.fill_between(x, y1, color='blue', alpha=0.15)
plt.show()

y2 = np.cos(1.2*x)
y3 = np.exp(-(x**2))
plt.figure()
plt.plot(x, y2, 'g--', label='y2=cos(1.2*x)')
plt.plot(x, y3, 'r', label='y3=exp(-x**2)')
plt.legend()
plt.title('plot of y2 and y3')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.show()